######################################################################
# Automatically generated by qmake (3.1) Sat Nov 1 15:37:26 2025
######################################################################

CONFIG += release
TEMPLATE = app
TARGET = awsmock-qt-ui
INCLUDEPATH += include
QT += network widgets charts
RESOURCES += resources/awsmock-qt-ui.qrc

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_UP_TO=0x060000 # disables all APIs deprecated in Qt 6.0.0 and earlier

# Input
HEADERS += include/mainwindow.h \
           include/utils/Configuration.h \
           include/utils/BasePage.h \
           include/utils/RestManager.h \
           include/utils/EditPreferencesDialog.h \
           include/utils/IconUtils.h \
           include/dto/sqs/SQSGetMessageDetailsResponse.h \
           include/dto/sqs/SQSQueueDetailsResponse.h \
           include/dto/sqs/UpdateQueueRequest.h \
           include/dto/sns/SNSGetMessageDetailsResponse.h \
           include/dto/sns/SNSGetTopicDetailsResponse.h \
           include/dto/sns/SNSListMessageResult.h \
           include/dto/sns/SNSListTopicResult.h \
           include/dto/sns/SNSMessageCounter.h \
           include/dto/sns/SNSTopicCounter.h \
           include/modules/dashboard/Dashboard.h \
           include/modules/sqs/SQSService.h \
           include/modules/sqs/SQSQueueList.h \
           include/modules/sqs/SQSMessageList.h \
           include/modules/sns/SNSMessageDetailsDialog.h \
           include/modules/sns/SNSService.h \
           include/modules/sns/SNSTopicList.h \
           include/modules/sns/SNSMessageList.h \
           include/modules/sns/SNSQueueList.h \
           include/modules/application/ApplicationList.h \
           include/modules/application/ApplicationService.h \
           include/modules/application/ApplicationAddDialog.h \
           include/modules/infrastructure/InfrastructureService.h
FORMS += src/modules/sqs/SQSQueueDetailsDialog.ui \
           src/modules/sqs/SQSMessageDetailsDialog.ui\
           src/modules/sns/SNSTopicDetailsDialog.ui \
           src/modules/sns/SNSMessageDetailsDialog.ui \
           src/modules/application/ApplicationEditDialog.ui
           src/modules/dashboard/Dashboard.ui
SOURCES += src/main.cpp \
           src/mainwindow.cpp \
           src/utils/Configuration.cpp \
           src/utils/BasePage.cpp \
           src/utils/RestManager.cpp \
           src/utils/EditPreferencesDialog.cpp \
           src/utils/IconUtils.cpp \
           src/modules/dashboard/Dashboard.cpp \
           src/modules/sqs/SQSMessageDetailsDialog.cpp \
           src/modules/sqs/SQSMessageList.cpp \
           src/modules/sqs/SQSQueueDetailsDialog.cpp \
           src/modules/sqs/SQSQueueList.cpp \
           src/modules/sqs/SQSService.cpp \
           src/modules/sqs/SQSQueueList.cpp \
           src/modules/sns/SNSMessageDetailsDialog.cpp \
           src/modules/sns/SNSMessageList.cpp \
           src/modules/sns/SNSService.cpp \
           src/modules/sns/SNSTopicDetailsDialog.cpp \
           src/modules/sns/SNSTopicList.cpp \
           src/modules/sns/ApplicationList.cpp \
           src/modules/sns/ApplicationService.cpp \
           src/modules/sns/ApplicationAddDialog.cpp \
           src/modules/infrastructure/InfrastructureService.cpp \
TRANSLATIONS += awsmock-qt-ui_en_150.ts
