//
// Created by jensv on 27/11/2025.
//

#ifndef AWSMOCK_QT_UI_VERSION_H_IN_H
#define AWSMOCK_QT_UI_VERSION_H_IN_H

#define AWSMOCK_UI_VERSION_MAJOR 1
#define AWSMOCK_UI_VERSION_MINOR 0
#define AWSMOCK_UI_VERSION_PATCH 10

#define AWSMOCK_UI_VERSION "1.0.10"

#endif //AWSMOCK_QT_UI_VERSION_H_IN_H
